# Generated by Django 4.2.6 on 2023-10-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rockets'),
        ),
    ]
