# Generated by Django 4.2.6 on 2023-10-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_rocket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocket',
            name='engine',
        ),
        migrations.AddField(
            model_name='rocket',
            name='fuel_condition',
            field=models.CharField(blank=True, choices=[('SRE', 'Solid rocket engine'), ('LRE', 'Liquid rocket engine'), ('H', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rocket',
            name='type',
            field=models.CharField(blank=True, choices=[('Light', 'Lightweight – up to 5 tons of payload'), ('Medium', 'Medium - from 5 to 20 tons'), ('Heavy', 'Heavy – from 20 to 100 tons'), ('Super_heavy', 'Super heavy – over 100 tons')], max_length=50, null=True),
        ),
    ]
