# Generated by Django 4.2.6 on 2023-10-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_remove_rocket_engine_rocket_fuel_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='fuel_condition',
            field=models.CharField(blank=True, choices=[('Solid rocket engine', 'SRE'), ('Liquid rocket engine', 'LRE'), ('Hybrid', 'H')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='type',
            field=models.CharField(blank=True, choices=[('Lightweight – up to 5 tons of payload', 'Light'), ('Medium - from 5 to 20 tons', 'Medium'), ('Heavy – from 20 to 100 tons', 'Heavy'), ('Super heavy – over 100 tons', 'Super_heavy')], max_length=50, null=True),
        ),
    ]
