# Generated by Django 4.2.6 on 2023-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_rocket_fuel_condition_alter_rocket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='fuel_condition',
            field=models.CharField(blank=True, choices=[('SRE', 'Solid rocket engine'), ('Liquid rocket engine', 'LRE'), ('H', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='type',
            field=models.CharField(blank=True, choices=[('Light', 'Lightweight – up to 5 tons of payload'), ('Medium', 'Medium - from 5 to 20 tons'), ('Heavy', 'Heavy – from 20 to 100 tons'), ('Super heavy', 'Super heavy – over 100 tons')], max_length=50, null=True),
        ),
    ]
