# Generated by Django 4.2.6 on 2023-10-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_alter_rocket_fuel_condition_alter_rocket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocket',
            name='manned',
        ),
        migrations.AlterField(
            model_name='rocket',
            name='fuel_condition',
            field=models.CharField(blank=True, choices=[('SRE', 'Solid rocket engine'), ('LRE', 'Liquid rocket engine'), ('H', 'Hybrid')], max_length=50, null=True),
        ),
    ]
